#!/usr/bin/env python3
# Copyright 2026, Nick Kennedy
# SPDX-License-Identifier: BSL-1.0
"""Generate compact Monado IPC wire metadata for the standalone proxy."""

import argparse
import json
from pathlib import Path


def load_calls(proto_dir: Path):
    calls = []
    for path in sorted(proto_dir.glob("*.json")):
        data = json.loads(path.read_text())
        for name, spec in data.items():
            if name.startswith("$"):
                continue
            calls.append((name, spec))
    return calls


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("proto_dir", type=Path)
    ap.add_argument("output", type=Path)
    ns = ap.parse_args()

    calls = load_calls(ns.proto_dir)
    out = []
    out.append("// Generated by scripts/generate_monado_proxy_wire.py")
    out.append("#pragma once")
    out.append("#include <stdbool.h>")
    out.append("#include <stddef.h>")
    out.append('#include "ipc_protocol_generated.h"')
    out.append("")
    out.append("static inline size_t macos_wine_xr_ipc_request_size(enum ipc_command cmd)")
    out.append("{")
    out.append("\tswitch (cmd) {")
    for name, spec in calls:
        cid = "IPC_" + name.upper()
        needs_msg = bool(spec.get("in")) or bool(spec.get("in_handles"))
        size = f"sizeof(struct ipc_{name}_msg)" if needs_msg else "sizeof(enum ipc_command)"
        out.append(f"\tcase {cid}: return {size};")
    out.append("\tdefault: return 0;")
    out.append("\t}")
    out.append("}")
    out.append("")
    out.append("static inline size_t macos_wine_xr_ipc_reply_size(enum ipc_command cmd)")
    out.append("{")
    out.append("\tswitch (cmd) {")
    for name, spec in calls:
        cid = "IPC_" + name.upper()
        if spec.get("varlen"):
            size = "0"
        elif spec.get("out"):
            size = f"sizeof(struct ipc_{name}_reply)"
        else:
            size = "sizeof(struct ipc_result_reply)"
        out.append(f"\tcase {cid}: return {size};")
    out.append("\tdefault: return 0;")
    out.append("\t}")
    out.append("}")
    out.append("")
    out.append("static inline bool macos_wine_xr_ipc_has_native_handles(enum ipc_command cmd)")
    out.append("{")
    out.append("\tswitch (cmd) {")
    for name, spec in calls:
        if spec.get("in_handles") or spec.get("out_handles"):
            out.append(f"\tcase IPC_{name.upper()}: return true;")
    out.append("\tdefault: return false;")
    out.append("\t}")
    out.append("}")
    ns.output.parent.mkdir(parents=True, exist_ok=True)
    ns.output.write_text("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
