#!/usr/bin/env python3
# Copyright 2026, Nick Kennedy
# SPDX-License-Identifier: BSL-1.0
"""Validate the Wine/proxy ABI and the native calls emitted by the proxy separately."""
from __future__ import annotations
import argparse
import json
import re
from pathlib import Path
from generate_monado_wire import load_calls, LOCAL, REQUIRED_NATIVE

COMMAND_RE = re.compile(r"^\s*(IPC_[A-Z0-9_]+),\s*$", re.MULTILINE)


def normalized(spec):
    # The proxy owns these types; their layout is identical to the frozen Wine ABI.
    return json.loads(json.dumps(spec).replace("mwxr_", ""))


def check(client_header, service_header, client_source, service_source):
    frozen = json.loads((Path(__file__).resolve().parents[1] / "protocol/monado-wine.json").read_text())
    client = COMMAND_RE.findall(client_header.read_text())
    expected = ["IPC_" + name.upper() for name in frozen]
    if not client or client != expected[:len(client)]:
        raise RuntimeError("Wine command IDs differ from the proxy's frozen Wine ABI")
    service = load_calls(service_source)
    service_commands = COMMAND_RE.findall(service_header.read_text())
    if service_commands != ["IPC_" + name.upper() for name, _ in service]:
        raise RuntimeError("Native headers do not match the selected Monado source; rebuild Monado")
    native = dict(service)
    client_specs = dict(load_calls(client_source))
    for name, spec in client_specs.items():
        if name not in frozen or normalized(frozen[name]) != spec:
            raise RuntimeError(f"Wine/proxy schema mismatch: {name}")
    sent = REQUIRED_NATIVE | {
        name for name, spec in frozen.items()
        if name not in LOCAL and not spec.get("in_handles") and not spec.get("out_handles")
    }
    for name in sent:
        if name not in native or native[name] != normalized(frozen[name]):
            raise RuntimeError(f"Native proxy/service schema mismatch: {name}")
    print(f"Wine/proxy ABI checked: {len(client)} commands; native proxy/service ABI checked: {len(sent)} commands")
    print("Native IDs are regenerated by name; transitional commands are terminated in the proxy")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--client-header", required=True, type=Path)
    ap.add_argument("--service-header", required=True, type=Path)
    ap.add_argument("--client-source", required=True, type=Path)
    ap.add_argument("--service-source", required=True, type=Path)
    args = ap.parse_args()
    check(args.client_header, args.service_header, args.client_source, args.service_source)


if __name__ == "__main__":
    main()
