#!/usr/bin/env python3
# Copyright 2026, Nick Kennedy
# SPDX-License-Identifier: BSL-1.0
"""Generate bounded little-endian codecs; no native ABI structs cross RPC."""
import argparse, hashlib, json
from pathlib import Path
p=argparse.ArgumentParser(); p.add_argument('--schema',required=True); p.add_argument('--output',required=True); a=p.parse_args()
data=Path(a.schema).read_bytes(); spec=json.loads(data)
primitives={'u64':('uint64_t',8),'i64':('int64_t',8),'u32':('uint32_t',4),'i32':('int32_t',4),'f32':('float',4),'char':('char',1)}
sizes={}
out=['// Generated by generate_openxr_rpc.py. Do not edit.','#pragma once','#include <stdint.h>','#include <string.h>',f'#define MWXR_RPC_VERSION {spec["version"]}u',f'#define MWXR_RPC_FINGERPRINT UINT64_C(0x{hashlib.sha256(data).hexdigest()[:16]})','#define MWXR_RPC_MAGIC 0x5258574du','enum mwxr_rpc_operation {']
out += [f' MWXR_OP_{n} = {i+1},' for i,n in enumerate(spec['operations'])]; out += ['};']
for name,fields in spec['records'].items():
    size=0; out += [f'struct mwxr_wire_{name} {{']
    for typ,field,*length in fields:
        ctype,n=primitives.get(typ,(f'struct mwxr_wire_{typ}',sizes.get(typ,0)))
        if not n: raise ValueError(f'Unknown or forward record {typ}')
        count=length[0] if length else 1; size += n*count
        out += [f' {ctype} {field}'+(f'[{count}]' if length else '')+';']
    sizes[name]=size; out += ['};',f'#define MWXR_WIRE_{name.upper()}_SIZE {size}u']
    for action in ['encode','decode']:
        out += [f'static inline void mwxr_{action}_{name}(uint8_t *bytes, '+('const ' if action=='encode' else '')+f'struct mwxr_wire_{name} *value) {{',' unsigned offset=0;']
        for typ,field,*length in fields:
            ctype,n=primitives.get(typ,(None,sizes.get(typ))); count=length[0] if length else 1
            out += [f' for (unsigned i=0;i<{count};++i) {{']
            access=f'value->{field}'+('[i]' if length else '')
            if typ not in primitives:
                out += [f' mwxr_{action}_{typ}(bytes+offset, &{access});']
            elif typ=='char':
                out += [f'bytes[offset]=(uint8_t){access};' if action=='encode' else f'{access}=(char)bytes[offset];']
            else:
                bits='uint64_t' if n==8 else 'uint32_t'
                out += [f' {bits} bits=0;']
                if action=='encode': out += [f' memcpy(&bits,&{access},{n});',f' for(unsigned j=0;j<{n};++j) bytes[offset+j]=(uint8_t)(bits>>(8*j));']
                else: out += [f' for(unsigned j=0;j<{n};++j) bits |= ({bits})bytes[offset+j]<<(8*j);',f' memcpy(&{access},&bits,{n});']
            out += [f' offset+={n};',' }']
        out += ['}']
out += [f'static inline int mwxr_rpc_operation_valid(uint32_t op) {{ return op>=1 && op<={len(spec["operations"])}; }}']
Path(a.output).parent.mkdir(parents=True,exist_ok=True); Path(a.output).write_text('\n'.join(out)+'\n')
