#!/usr/bin/env python3
# Copyright 2026, Nick Kennedy
# SPDX-License-Identifier: BSL-1.0
"""Generate the minimal Monado IPC wire description used by the Wine proxy."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import hashlib
from pathlib import Path


LOCAL = {
    "instance_get_shm_chunk", "compositor_layer_copy_chunk",
    "compositor_layer_sync_copy_commit", "compositor_layer_sync_copy_commit_semaphore",
    "compositor_layer_sync_single", "compositor_layer_sync_single_semaphore",
    "compositor_layer_sync_single_semaphore_async", "swapchain_import_metal_bootstrap",
    "compositor_semaphore_import_metal_bootstrap",
}
REQUIRED_NATIVE = {
    "instance_get_shm_fd", "compositor_layer_sync", "compositor_layer_sync_with_semaphore",
    "swapchain_import_metal", "compositor_semaphore_import_metal",
}


def load_calls(monado: Path):
    proto_dir = monado / "src/xrt/ipc/shared/proto"
    calls = []
    for path in sorted(proto_dir.glob("*.json")):
        if path.name.endswith("schema.json"):
            continue
        data = json.loads(path.read_text())
        for name, spec in data.items():
            if name.startswith("$"):
                continue
            calls.append((name, spec))
    return calls


def field(arg):
    return f"\t{arg['type']} {arg['name']};"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--monado-source", required=True, type=Path)
    ap.add_argument("--output", required=True, type=Path)
    ap.add_argument("--generated-header", type=Path)
    ap.add_argument("--expected-revision")
    args = ap.parse_args()

    native_calls = load_calls(args.monado_source)
    calls = list(json.loads((Path(__file__).resolve().parents[1] / "protocol/monado-wine.json").read_text()).items())
    native_ids = {name: i for i, (name, _) in enumerate(native_calls, start=1)}
    native_specs = dict(native_calls)
    sent = REQUIRED_NATIVE | {
        name for name, spec in calls
        if name not in LOCAL and not spec.get("in_handles") and not spec.get("out_handles")
    }
    wine_specs = dict(calls)
    for name in sent:
        spec = json.loads(json.dumps(wine_specs[name]).replace("mwxr_", ""))
        if name not in native_specs or spec != native_specs[name]:
            raise RuntimeError(f"Native proxy/service wire layout changed: {name}")
    revision = subprocess.check_output(["git", "-C", str(args.monado_source), "rev-parse", "HEAD"], text=True).strip()
    if args.expected_revision is not None and revision != args.expected_revision:
        raise RuntimeError(f"Monado header revision changed: configured {args.expected_revision}, current {revision}; reconfigure the proxy against the new build")
    digest = hashlib.sha256()
    for path in sorted((args.monado_source / "src/xrt/ipc/shared").rglob("*")):
        if path.is_file() and (path.suffix == ".json" or path.name == "ipc_protocol.h"):
            digest.update(path.read_bytes())
    if args.generated_header is not None:
        generated = args.generated_header.read_text()
        actual = re.findall(r"^\s*(IPC_[A-Z0-9_]+),\s*$", generated, re.MULTILINE)
        expected = ["IPC_" + name.upper() for name, _ in native_calls]
        if actual != expected:
            mismatch = next(
                (i for i, pair in enumerate(zip(actual, expected)) if pair[0] != pair[1]),
                min(len(actual), len(expected)),
            )
            got = actual[mismatch] if mismatch < len(actual) else "<end>"
            want = expected[mismatch] if mismatch < len(expected) else "<end>"
            raise RuntimeError(
                f"Monado IPC command ordering mismatch at index {mismatch + 1}: "
                f"generated header has {got}, schema-derived proxy expects {want}. "
                "Reconfigure/rebuild the matching Monado tree before building the proxy."
            )
    out = []
    out += [f'#define MWXR_MONADO_REVISION "{revision}"', f'#define MWXR_MONADO_PROTOCOL_SHA256 "{digest.hexdigest()}"']
    out += [
        "// Generated by tools/generate_monado_wire.py. Do not edit.",
        "// SPDX-License-" + "Identifier: BSL-1.0",
        "#pragma once",
        "",
        '#include "shared/ipc_protocol.h"',
        "#include <stdbool.h>",
        "#include <stddef.h>",
        "#include <stdint.h>",
        '#include "monado_wine_types.h"',
        "",
    ]
    for name, i in native_ids.items():
        out.append(f"#define NATIVE_IPC_{name.upper()} {i}")
    out += ["typedef enum mwxr_ipc_command {", "\tMWXR_IPC_ERR = 0,"]
    for i, (name, _) in enumerate(calls, start=1):
        out.append(f"\tIPC_{name.upper()} = {i},")
    out += ["} mwxr_ipc_command_t;", "", "struct mwxr_ipc_command_msg { uint32_t cmd; };",
            "struct mwxr_ipc_result_reply { xrt_result_t result; };", "",
            "#pragma pack(push, 1)"]

    for name, spec in calls:
        in_args = spec.get("in", [])
        in_handles = spec.get("in_handles")
        if in_args or in_handles:
            out.append(f"struct ipc_{name}_msg")
            out.append("{")
            out.append("\tuint32_t cmd;")
            out.extend(field(a) for a in in_args)
            if in_handles:
                out.append("\tuint32_t handle_count;")
            out.append("};")
            out.append("")
        out_args = spec.get("out", [])
        if out_args:
            out.append(f"struct ipc_{name}_reply")
            out.append("{")
            out.append("\txrt_result_t result;")
            out.extend(field(a) for a in out_args)
            out.append("};")
            out.append("")

    out += ["#pragma pack(pop)", "",
            "struct mwxr_wire_info {",
            "\tsize_t request_size;",
            "\tsize_t reply_size;",
            "\tbool one_way;",
            "\tbool in_handles;",
            "\tbool out_handles;",
            "\tbool varlen;",
            "};", "",
            "static inline struct mwxr_wire_info",
            "mwxr_wire_info_for(uint32_t cmd)",
            "{",
            "\tswitch (cmd) {"]

    for name, spec in calls:
        in_args = spec.get("in", [])
        in_handles = bool(spec.get("in_handles"))
        out_handles = bool(spec.get("out_handles"))
        varlen = bool(spec.get("varlen"))
        req = f"sizeof(struct ipc_{name}_msg)" if (in_args or in_handles) else "sizeof(uint32_t)"
        out_args = spec.get("out", [])
        one_way = name == "compositor_layer_sync_single_semaphore_async"
        reply = "0" if one_way else (f"sizeof(struct ipc_{name}_reply)" if out_args else "sizeof(struct mwxr_ipc_result_reply)")
        out.append(
            f"\tcase IPC_{name.upper()}: return (struct mwxr_wire_info)"
            f"{{{req}, {reply}, {'true' if one_way else 'false'}, "
            f"{'true' if in_handles else 'false'}, {'true' if out_handles else 'false'}, {'true' if varlen else 'false'}}};"
        )
    out += [
        "\tdefault: return (struct mwxr_wire_info){0, 0, false, false, false};",
        "\t}",
        "}",
        "",
    ]

    out += ["static inline uint32_t mwxr_native_command(uint32_t cmd)", "{", "\tswitch (cmd) {"]
    for name, _ in calls:
        if name not in LOCAL and name in native_ids:
            out.append(f"\tcase IPC_{name.upper()}: return NATIVE_IPC_{name.upper()};")
    out += ["\tdefault: return 0;", "\t}", "}", ""]

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(out))


if __name__ == "__main__":
    main()
